Error CS0219 in project AGSEditor, file MidiPlayer.cs
Unused variable. Removed variable, but kept function call that assigned to it as there is stuff happening in the code behind.