Error CS0414 in project AGS.CScript.Compiler, ScalarVariableTypeToken.cs
Unused variable. I couldn't find that it did anything and removing it doesn't seem to break anything obvious.