Error CS0414 in project AGSEditor, file AGSEditor.cs
Write only variable "ApplicationStarted" was unused, solved by adding a getter as I can't think of a good reason this variable shouldn't have one.