Error CS0414 in project AGS.CScript.Compiler, file OperatorToken.cs
Unused variable. This one seem to had a great deal of thought put into it with a full Enum list to go with it. I decided to fix this by adding a getter just in case.