Error CS1587 in project AGS.Types, file EnumTypeConverter.cs
File header is commented with /* */ which xbuild doesn't approve of for some reason. I replaced the comments with something more conventional. Alternatively we could also consider to just remove the header entirely, the revision history doesn't provide much substantial information.