Error CS0414 in project AGS.Types, file DialogOption.cs
xBuild doesn't approve of unused variable, property documentation insists that this dummy variable is needed so I just fixed it with a pragma warning disable.