Error CS0219 in project AGS.CScript.Compiler, file ScriptsComponent.cs
Unused variable. Removed it but kept the function call that assigned the variable as there is stuff happening in the code-behind.