Error CS0219 in project AGSEditor, file ImportExport.cs
Two unused variables at the end of a function. Looks like they can just be removed, however they almost look like they were intended to be used for something so I commented them instead.